apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: healthcheck-timeout
on:
  workflow_dispatch:
jobs:
  build:
    services:
      aservice:
        image: redis
        entrypoint: "docker-entrypoint.sh"
        args: "redis-server"
        healthcheck:
          cmd: |
           sleep 20
           redis-cli ping
          timeout-seconds: 10
    steps:
      - name: Say hello
        uses: docker://redis
        shell: sh
        run: |
          redis-cli SET testkey "Hello Redis!"
          redis-cli GET testkey
