apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: no image
on:
  workflow_dispatch:
jobs:
  build:
    services:
      aservice:
        image: 
        entrypoint: "docker-entrypoint.sh"
    steps:
      - name: Say hello
        uses: docker://redis:7-alpine3.20
        shell: sh
        run: |
          redis-cli SET testkey "Hello Redis!"
          redis-cli GET testkey
