apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: redis
on:
  workflow_dispatch:
jobs:
  build:
    steps:
      - uses: docker://redis:7-alpine3.20
        name: Run Redis commands
        run: |
          sleep 60
          redis-cli SET testkey "Hello Redis!"
          redis-cli GET testkey
