apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: postgress

on:
  workflow_dispatch:

jobs:
  generate:
    services:
      postgres:
        image: docker://postgres:13
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5433
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        healthcheck:
          cmd: pg_isready -U testuser -d testdb -p 5433
          timeout-seconds: 120
    steps:
      - uses: docker://postgres:13
        name: Say hello
        shell: sh
        run: |
          pg_isready -U testuser -d testdb -h localhost -p 5433