apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: sidecar
on:
  workflow_dispatch:

jobs:
  build:

    steps:
      - name: Run tests against postgres db
        uses: docker://postgres:13
        env:
          DATABASE_URL: postgres://testuser:testpassword@localhost:5432/testdb
        run: |
          echo "DATABASE_URL is $DATABASE_URL"
          # Replace this with your actual test command
          psql -h localhost -U testuser -d testdb -c "SELECT 'Hello, PostgreSQL!' AS greeting;"
