apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: sidecar
on:
  workflow_dispatch:

jobs:
  build:
    services:
      postgres:
        image: docker://postgres:13
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb1
        healthcheck:
          cmd: pg_isready -U testuser -d testdb
          timeout-seconds: 7
        entrypoint: docker-entrypoint.sh
        args:
          - postgres
    steps:
      - name: Run tests against postgres db
        uses: docker://postgres:13
        env:
          DATABASE_URL: postgres://testuser:testpassword@localhost:5432/testdb
        run: |
          echo "DATABASE_URL is $DATABASE_URL"
          # Replace this with your actual test command
          psql -h localhost -U testuser -d testdb -c "SELECT 'Hello, PostgreSQL!' AS greeting;"
