apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: redis
on:
  workflow_dispatch:
permissions:
  scm-token-own: read
  scm-token-org: read
  id-token: write
jobs:
  build:
    if: ${{ vars.workflow_execution_env == 'staging' }}
    services:
      redis:
        image: docker://redis:7-alpine3.20
        healthcheck:
          cmd: redis-cli ping
          timeout-seconds: 5
    steps:
      - name: Wait for Redis service to be healthy
        uses: docker://redis:7-alpine3.20
        run: |
          until redis-cli -h localhost -p 6379 ping | grep PONG; do
            echo "Waiting for Redis...";
            sleep 5;
          done
      - name: Run Redis commands
        uses: docker://redis:7-alpine3.20
        run: |
          redis-cli -h localhost -p 6379 SET testkey "Hello Redis!"
          redis-cli -h localhost -p 6379 GET testkey
