apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: redis
on:
  workflow_dispatch:
jobs:
  build:
    services:
      redis:
        image: docker://redis:7-alpine3.20
        healthcheck:
          cmd: "redis-cli ping"
          timeout-seconds: 10
    steps:
      - name: Run Redis commands
        uses: docker://redis:7-alpine3.20
        run: |
          redis-cli SET testkey "Hello Redis!"
          redis-cli GET testkey
