apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: redis
on:
  workflow_dispatch:
jobs:
  build:
    services:
      redis:
        image: docker://redis:7-alpine3.20
        # entrypoint: "docker-entrypoint.sh"
        # healthcheck:
          # cmd: |-
            # redis-cli ping
            # sleep 120
          # timeout-seconds: 10
    steps:
      - uses: docker://redis:7-alpine3.20
        name: Run Redis commands
        run: |
          sleep 180
          redis-cli SET testkey "Hello Redis!"
          redis-cli GET testkey
