apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: sidecar test
on:
 workflow_dispatch:
jobs:
  build:
    services:
      redis:
        image: docker://redis:7-alpine3.20
        entrypoint: "caca-entrypoint.sh"
    steps:
      # Connecting to Redis and executing commands
      - name: Run Redis commands
        uses: docker://redis:7-alpine3.20
        run: |
          redis-cli -h localhost -p 6379 SET testkey "Hello Redis!"
          redis-cli -h localhost -p 6379 GET testkey
