apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: redis
on:
  workflow_dispatch:
permissions:
  scm-token-own: read
  scm-token-org: read
  id-token: write
jobs:
  build:
    services:
      redis:
        image: docker://redis:7-alpine3.20
        healthcheck:
          cmd: awrongcommand
          timeout-seconds: 120
      postgres:
        image: docker://postgres:13
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        healthcheck:
          cmd: pg_isready -U testuser -d testdb
          timeout-seconds: 7
        entrypoint: "docker-entrypoint.sh"
        args: ["postgres"]
    steps:
      - name: Run Redis commands
        uses: docker://redis:7-alpine3.20
        run: |
          redis-cli -h localhost -p 6379 SET testkey "Hello Redis!"
          redis-cli -h localhost -p 6379 GET testkey