apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: sidecar test 2
on:
  workflow_dispatch:
jobs:
  build:
    services:
      server:
        image: docker://redis:7-alpine3.20
        healthcheck:
          cmd: | 
            until redis-cli -h localhost -p 6379 ping | grep PONG; do
              echo "Waiting for Redis...";
              sleep 5;
            done
          timeout-seconds: 60
    steps:

      - name: Run Redis commands
        uses: docker://redis:7-alpine3.20
        run: |
          redis-cli -h localhost -p 6379 SET testkey "Hello Redis!"
          redis-cli -h localhost -p 6379 GET testkey

