apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: sidecar test 2
on:
  workflow_dispatch:
jobs:
  build:
    services:
      server:
        image: docker:18.05-dind
        
    steps:

      - name: Run Redis commands
        uses: docker://redis:7-alpine3.20
        run: |
          redis-cli -h localhost -p 6379 SET testkey "Hello Redis!"
          redis-cli -h localhost -p 6379 GET testkey

