apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: what the workflow
on:
  workflow_dispatch:
jobs:
  build:
    services:
      aservice:
        image: redis
        entrypoint: "/bin/echo 'hello entrypoint'"
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
