apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: what the workflow
on:
  workflow_dispatch:
jobs:
  build:
    services:
      aservice:
        image: redis
        entrypoint: "docker-entrypoin222t.sh"
    steps:
      - name: Say hello
        uses: docker://redis
        shell: sh
        run: |
          redis-cli SET testkey "Hello Redis!"
          redis-cli GET testkey

