apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: what the workflow
on:
  workflow_dispatch:
jobs:
  build:
    services:
      aservice:
        image: redis
        entrypoint: "docker-entrypoint.sh"
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          redis-cli -h localhost -p 6379 SET testkey "Hello Redis!"
          redis-cli -h localhost -p 6379 GET testkey
