apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: wrong healthcheck
on:
  workflow_dispatch:

jobs:
  build:
    services:
      redis:
        image: redis
        entrypoint: caca

    steps:
      - uses: docker://redis:7-alpine3.20
        name: Run Redis commands
        run: |
          redis-cli SET testkey "Hello Redis!"
          redis-cli GET testkey
