apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: wrong healthcheck
on:
  workflow_dispatch:
permissions:
  scm-token-own: read
  scm-token-org: read
  id-token: write
jobs:
  build:
    services:
      redis:
        image: redis
        entrypoint: caca
        healthcheck:
          cmd: awrongcommand
          timeout-seconds: 120
    steps:
      - uses: docker://redis:7-alpine3.20
        name: Run Redis commands
        run: |
          redis-cli SET testkey "Hello Redis!"
          redis-cli GET testkey
