apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: wrong image service
on:
  workflow_dispatch:

jobs:
  build:
    services:
      redis:
        image: wrong
        entrypoint: caca
      redis2:
        image: wrong
        entrypoint: caca
      redis3:
        image: wrong
        entrypoint: caca
    steps:
      - name: Run Redis commands
        uses: docker://redis:7-alpine3.20
        run: |
          redis-cli -h localhost -p 6379 SET testkey "Hello Redis!"
          redis-cli -h localhost -p 6379 GET testkey
