
apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: sidecar

on:
  workflow_dispatch:

jobs:
  build:
    services:
      redis:
        image: redis:7-alpine3.20
        entrypoint: "docker-entrypoint.sh"
        healthcheck:
          cmd: "redis-cli -h 192.0.1.0 ping"
          timeout-seconds: 5
    
    steps:
      # Connecting to Redis and executing commands
      - name: Run Redis commands
        uses: docker://redis:7-alpine3.20
        run: |
          redis-cli SET testkey "Hello Redis!"
          redis-cli GET testkey
